// `astro:env/server` is a virtual module generated by `astro sync`; Vite outside
// the Astro build cannot resolve it, so vitest.config.ts aliases it here.
//
// Every value is `undefined`, which is what an unconfigured deployment sees. That
// is deliberate: the email seam then selects `devLogAdapter` at import time, and a
// unit test that wants a different adapter installs one through `setEmailAdapter`
// — the same injection point the integration fakes use. A test must never depend
// on a real key leaking in from the developer's shell.

export const SUPABASE_URL: string | undefined = undefined;
export const SUPABASE_KEY: string | undefined = undefined;
export const RESEND_API_KEY: string | undefined = undefined;
export const EMAIL_FROM: string | undefined = undefined;
